# Minimal settings
global:
  shell:
    port: 22
  edition: ce
  ingress:
    enabled: true
    configureCertmanager: false
    class: "nginx"
  hosts:
    domain: domain.com
    externalIP: 
  rails:
    bootsnap:
      enabled: false
# Don't use certmanager, we'll self-sign
certmanager:
  install: false
# Use the `ingress` addon, not our Ingress (can't map 22/80/443)
nginx-ingress:
  enabled: true
  tcp: {} # disable binding to `22` on host 
  controller:
    hostNetwork: false
    daemonset:
      useHostPort: false
      hostPorts:
        http: 80
        https: 443
      kind: DaemonSet
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
prometheus:
  install: false
runners:
  install: false
  privileged: false
# GitLab Runner isn't a big fan of self-signed certificates
gitlab-runner:
  install: false
rbac:
  create: true
