apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-19T14:53:20Z"
  labels:
    app.kubernetes.io/instance: netbox-test
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: netbox
    app.kubernetes.io/version: 2.8.3
    helm.sh/chart: netbox-2.2.0
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-05-19T14:53:20Z"
  name: netbox-test
  namespace: netdevbox
  resourceVersion: "5455"
  selfLink: /api/v1/namespaces/netdevbox/services/netbox-test
  uid: f0ee8fef-b64e-45fb-b7ca-a3514c149304
spec:
  clusterIP: 10.152.183.58
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: netbox-test
    app.kubernetes.io/name: netbox
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
