  # Ingress allows ingress services to be created to allow external access
  # from Kubernetes to access Vault pods.
  ingress:
    enabled: true
    labels: 
      traffic: external
    annotations: 
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: vault.local
        paths: 
          - /

    tls: 
      - secretName: vault-local-tls
        hosts:
          - vault.local

 auditStorage:
    enabled: true

ui:
  enabled: true
  serviceType: "LoadBalancer"
  serviceNodePort: null
  externalPort: 8200

  loadBalancerSourceRanges:
     - 10.0.0.0/8
     - 172.16.0.0/12
     - 192.168.0.0/16

